def arch_id() -> str {
    "x86_64-linux"
};

def arch_word() -> long {
    8
};

def arch_sysno(name: str) -> long {
    if (name == "read") { 0 }
    else if (name == "write") { 1 }
    else if (name == "close") { 3 }
    else if (name == "openat") { 257 }
    else if (name == "exit") { 60 }
    else { -1 }
};

def arch_fn_label(uid: long, name: str) -> str {
    "yfn_" + tostring(uid) + "_" + name
};

def arch_loc_label(fuid: long, n: long) -> str {
    "yL_" + tostring(fuid) + "_" + tostring(n)
};

def arch_str_label(i: long) -> str {
    "ystr_" + tostring(i)
};

def arch_header() -> str {
    ".text\n.globl _start\n"
};

def arch_rodata() -> str {
    ".section .rodata\n"
};

def arch_text() -> str {
    ".text\n"
};

def arch_frame(slots: long) -> long {
    let bytes = slots * 8;
    if (bytes % 16 == 0) { bytes } else { bytes + (16 - bytes % 16) }
};

def arch_exit() -> str {
    "    mov \$60, %rax\n    xor %edi, %edi\n    syscall\n"
};

def arch_prelude() -> str {
    join([
        "y_print_long:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    sub $48, %rsp",
        "    mov %rdi, %rax",
        "    xor %r8d, %r8d",
        "    test %rax, %rax",
        "    jns ypl_loop",
        "    neg %rax",
        "    mov $1, %r8d",
        "ypl_loop:",
        "    mov %rbp, %rcx",
        "    mov $10, %r10",
        "ypl_dig:",
        "    xor %edx, %edx",
        "    div %r10",
        "    add $48, %rdx",
        "    dec %rcx",
        "    mov %dl, (%rcx)",
        "    test %rax, %rax",
        "    jnz ypl_dig",
        "    cmp $0, %r8d",
        "    jz ypl_go",
        "    dec %rcx",
        "    movb $45, (%rcx)",
        "ypl_go:",
        "    mov %rcx, %rsi",
        "    mov %rbp, %rdx",
        "    sub %rcx, %rdx",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    syscall",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    lea ystr_nl(%rip), %rsi",
        "    mov $1, %rdx",
        "    syscall",
        "    add $48, %rsp",
        "    pop %rbp",
        "    ret",
        "y_print_bool:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    test %rdi, %rdi",
        "    jz ypb_f",
        "    lea ystr_true(%rip), %rsi",
        "    mov $4, %rdx",
        "    jmp ypb_go",
        "ypb_f:",
        "    lea ystr_false(%rip), %rsi",
        "    mov $5, %rdx",
        "ypb_go:",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    syscall",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    lea ystr_nl(%rip), %rsi",
        "    mov $1, %rdx",
        "    syscall",
        "    pop %rbp",
        "    ret",
        "y_print_hstr:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    mov %rdi, %rbx",
        "    mov %rbx, %rsi",
        "    add $8, %rsi",
        "    mov (%rbx), %rdx",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    syscall",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    lea ystr_nl(%rip), %rsi",
        "    mov $1, %rdx",
        "    syscall",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_str_eq:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    mov 24(%rbp), %rbx",
        "    mov 16(%rbp), %r13",
        "    test %rbx, %rbx",
        "    jnz yse_aok",
        "    test %r13, %r13",
        "    jnz yse_no",
        "    mov $1, %rax",
        "    jmp yse_done",
        "yse_aok:",
        "    test %r13, %r13",
        "    jz yse_no",
        "    mov (%rbx), %rcx",
        "    mov (%r13), %rdx",
        "    cmp %rdx, %rcx",
        "    jnz yse_no",
        "    mov %rbx, %rbx",
        "    add $8, %rbx",
        "    mov %r13, %r13",
        "    add $8, %r13",
        "    xor %r8d, %r8d",
        "yse_loop:",
        "    mov %rcx, %rax",
        "    sub %r8, %rax",
        "    sub $8, %rax",
        "    jb yse_tail",
        "    mov (%rbx,%r8,1), %rax",
        "    mov (%r13,%r8,1), %rdx",
        "    cmp %rdx, %rax",
        "    jnz yse_no",
        "    add $8, %r8",
        "    jmp yse_loop",
        "yse_tail:",
        "    mov %rcx, %r8",
        "    sub $8, %r8",
        "    mov (%rbx,%r8,1), %rax",
        "    mov (%r13,%r8,1), %rdx",
        "    cmp %rdx, %rax",
        "    jnz yse_no",
        "    mov $1, %rax",
        "    jmp yse_done",
        "yse_no:",
        "    xor %eax, %eax",
        "yse_done:",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_str_cmp:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    mov 24(%rbp), %rbx",
        "    mov 16(%rbp), %r13",
        "    mov (%rbx), %rcx",
        "    mov (%r13), %rdx",
        "    add $8, %rbx",
        "    add $8, %r13",
        "    xor %r8d, %r8d",
        "ysc_loop:",
        "    cmp %rcx, %r8",
        "    jge ysc_aend",
        "    cmp %rdx, %r8",
        "    jge ysc_pos",
        "    movzbq (%rbx,%r8,1), %rax",
        "    movzbq (%r13,%r8,1), %r14",
        "    cmp %r14, %rax",
        "    jl ysc_neg",
        "    jg ysc_pos",
        "    inc %r8",
        "    jmp ysc_loop",
        "ysc_aend:",
        "    cmp %rdx, %r8",
        "    jge ysc_zero",
        "ysc_neg:",
        "    mov $-1, %rax",
        "    jmp ysc_done",
        "ysc_pos:",
        "    mov $1, %rax",
        "    jmp ysc_done",
        "ysc_zero:",
        "    xor %eax, %eax",
        "ysc_done:",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_str_cat:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    push %r12",
        "    mov 24(%rbp), %rbx",
        "    mov 16(%rbp), %r13",
        "    mov (%rbx), %rcx",
        "    mov (%r13), %rdx",
        "    add %rdx, %rcx",
        "    mov %rcx, %rdi",
        "    add $16, %rdi",
        "    mov %rcx, %r12",
        "    call y_alloc",
        "    mov %rax, %r14",
        "    mov %rbx, %rsi",
        "    add $8, %rsi",
        "    mov %r14, %rdi",
        "    add $8, %rdi",
        "    mov (%rbx), %rcx",
        "    call ysc_copy",
        "    mov %r13, %rsi",
        "    add $8, %rsi",
        "    mov (%rbx), %rdx",
        "    mov %rdi, %rdi",
        "    add %rdx, %rdi",
        "    mov (%r13), %rcx",
        "    test %rcx, %rcx",
        "    jz ysc_skip2",
        "    call ysc_copy",
        "ysc_skip2:",
        "    mov %r12, (%r14)",
        "    mov %r12, %rbx",
        "    movb $0, 8(%r14,%rbx,1)",
        "    mov %r14, %rax",
        "    pop %r12",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "ysc_copy:",
        "    mov %rcx, %rax",
        "    add $7, %rax",
        "    shr $3, %rax",
        "    xor %r8d, %r8d",
        "yscc_loop:",
        "    cmp %rax, %r8",
        "    jge yscc_done",
        "    mov (%rsi,%r8,8), %rdx",
        "    mov %rdx, (%rdi,%r8,8)",
        "    inc %r8",
        "    jmp yscc_loop",
        "yscc_done:",
        "    ret",
        "y_div_zero:",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    lea ystr_divzero(%rip), %rsi",
        "    mov $ystr_divzero_end-ystr_divzero, %rdx",
        "    syscall",
        "    mov $60, %rax",
        "    mov $1, %rdi",
        "    syscall",
        "y_oob:",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    lea ystr_oob(%rip), %rsi",
        "    mov $ystr_oob_end-ystr_oob, %rdx",
        "    syscall",
        "    mov $60, %rax",
        "    mov $1, %rdi",
        "    syscall",
        "y_dot_lookup:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    push %r15",
        "    mov 24(%rbp), %rbx",
        "    mov 16(%rbp), %r13",
        "    test %rbx, %rbx",
        "    jz y_dot_trap",
        "    mov -8(%rbx), %r14",
        "    mov (%r14), %r10",
        "    mov $1498307412, %rax",
        "    cmp %rax, %r10",
        "    jnz y_dot_trap",
        "    mov 8(%r14), %r15",
        "    lea 16(%r14), %r14",
        "    mov (%r13), %r10",
        "    mov %r13, %r11",
        "    add $8, %r11",
        "ydl_next:",
        "    test %r15, %r15",
        "    jz y_dot_trap",
        "    dec %r15",
        "    mov 8(%r14), %rcx",
        "    cmp %r10, %rcx",
        "    jnz ydl_skip",
        "    xor %edx, %edx",
        "ydl_cmp:",
        "    cmp %r10, %rdx",
        "    jge ydl_hit",
        "    movzbq 16(%r14,%rdx,8), %rax",
        "    movzbq (%r11,%rdx,1), %rcx",
        "    cmp %rcx, %rax",
        "    jnz ydl_skip",
        "    inc %rdx",
        "    jmp ydl_cmp",
        "ydl_hit:",
        "    mov (%r14), %rax",
        "    add %rbx, %rax",
        "    mov (%rax), %rax",
        "    jmp ydl_ret",
        "ydl_skip:",
        "    mov 8(%r14), %rax",
        "    shl $3, %rax",
        "    add $16, %rax",
        "    add %rax, %r14",
        "    jmp ydl_next",
        "ydl_ret:",
        "    pop %r15",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_dot_trap:",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    lea ystr_dot(%rip), %rsi",
        "    mov $ystr_dot_end-ystr_dot, %rdx",
        "    syscall",
        "    mov %r13, %rdi",
        "    call y_put_hstr",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    lea ystr_dot2(%rip), %rsi",
        "    mov $ystr_dot2_end-ystr_dot2, %rdx",
        "    syscall",
        "    mov $60, %rax",
        "    mov $1, %rdi",
        "    syscall",
        "y_alloc:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r12",
        "    mov %rdi, %rbx",
        "    add $15, %rbx",
        "    and $-8, %rbx",
        "    mov $12, %rax",
        "    xor %edi, %edi",
        "    syscall",
        "    mov %rax, %r12",
        "    mov %r12, %rdi",
        "    add %rbx, %rdi",
        "    mov $12, %rax",
        "    syscall",
        "    mov %r12, %rdx",
        "    add %rbx, %rdx",
        "    cmp %rdx, %rax",
        "    jb y_alloc_fail",
        "    mov %r12, %rax",
        "    pop %r12",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_alloc_fail:",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    lea ystr_oom(%rip), %rsi",
        "    mov $ystr_oom_end-ystr_oom, %rdx",
        "    syscall",
        "    mov $60, %rax",
        "    mov $1, %rdi",
        "    syscall",
        "y_opt_unwrap:",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    lea ystr_opt(%rip), %rsi",
        "    mov $ystr_opt_end-ystr_opt, %rdx",
        "    syscall",
        "    mov $60, %rax",
        "    mov $1, %rdi",
        "    syscall",
        "y_put_long:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    sub $48, %rsp",
        "    mov %rdi, %rax",
        "    xor %r8d, %r8d",
        "    test %rax, %rax",
        "    jns ypl2_loop",
        "    neg %rax",
        "    mov $1, %r8d",
        "ypl2_loop:",
        "    mov %rbp, %rcx",
        "    mov $10, %r10",
        "ypl2_dig:",
        "    xor %edx, %edx",
        "    div %r10",
        "    add $48, %rdx",
        "    dec %rcx",
        "    mov %dl, (%rcx)",
        "    test %rax, %rax",
        "    jnz ypl2_dig",
        "    cmp $0, %r8d",
        "    jz ypl2_go",
        "    dec %rcx",
        "    movb $45, (%rcx)",
        "ypl2_go:",
        "    mov %rcx, %rsi",
        "    mov %rbp, %rdx",
        "    sub %rcx, %rdx",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    syscall",
        "    add $48, %rsp",
        "    pop %rbp",
        "    ret",
        "y_put_bool:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    test %rdi, %rdi",
        "    jz ypb2_f",
        "    lea ystr_true(%rip), %rsi",
        "    mov $4, %rdx",
        "    jmp ypb2_go",
        "ypb2_f:",
        "    lea ystr_false(%rip), %rsi",
        "    mov $5, %rdx",
        "ypb2_go:",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    syscall",
        "    pop %rbp",
        "    ret",
        "y_put_hstr:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    mov %rdi, %rbx",
        "    mov %rbx, %rsi",
        "    add $8, %rsi",
        "    mov (%rbx), %rdx",
        "    mov $1, %rax",
        "    mov $1, %rdi",
        "    syscall",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_eput_long:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    sub $48, %rsp",
        "    mov %rdi, %rax",
        "    xor %r8d, %r8d",
        "    test %rax, %rax",
        "    jns ypl3_loop",
        "    neg %rax",
        "    mov $1, %r8d",
        "ypl3_loop:",
        "    mov %rbp, %rcx",
        "    mov $10, %r10",
        "ypl3_dig:",
        "    xor %edx, %edx",
        "    div %r10",
        "    add $48, %rdx",
        "    dec %rcx",
        "    mov %dl, (%rcx)",
        "    test %rax, %rax",
        "    jnz ypl3_dig",
        "    cmp $0, %r8d",
        "    jz ypl3_go",
        "    dec %rcx",
        "    movb $45, (%rcx)",
        "ypl3_go:",
        "    mov %rcx, %rsi",
        "    mov %rbp, %rdx",
        "    sub %rcx, %rdx",
        "    mov $1, %rax",
        "    mov $2, %rdi",
        "    syscall",
        "    add $48, %rsp",
        "    pop %rbp",
        "    ret",
        "y_eput_bool:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    test %rdi, %rdi",
        "    jz ypb3_f",
        "    lea ystr_true(%rip), %rsi",
        "    mov $4, %rdx",
        "    jmp ypb3_go",
        "ypb3_f:",
        "    lea ystr_false(%rip), %rsi",
        "    mov $5, %rdx",
        "ypb3_go:",
        "    mov $1, %rax",
        "    mov $2, %rdi",
        "    syscall",
        "    pop %rbp",
        "    ret",
        "y_eput_hstr:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    mov %rdi, %rbx",
        "    mov %rbx, %rsi",
        "    add $8, %rsi",
        "    mov (%rbx), %rdx",
        "    mov $1, %rax",
        "    mov $2, %rdi",
        "    syscall",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_clock_us:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    sub $16, %rsp",
        "    mov $228, %rax",
        "    mov $1, %rdi",
        "    lea -16(%rbp), %rsi",
        "    syscall",
        "    mov -8(%rbp), %rax",
        "    xor %edx, %edx",
        "    mov $1000, %r10",
        "    div %r10",
        "    mov -16(%rbp), %rcx",
        "    mov $1000000, %r10",
        "    imul %r10, %rcx",
        "    add %rcx, %rax",
        "    mov %rbp, %rsp",
        "    pop %rbp",
        "    ret",
        "y_sleep:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    sub $16, %rsp",
        "    test %rdi, %rdi",
        "    jns ysl_pos",
        "    xor %edi, %edi",
        "ysl_pos:",
        "    mov %rdi, %rax",
        "    xor %edx, %edx",
        "    mov $1000, %r10",
        "    div %r10",
        "    mov %rax, -16(%rbp)",
        "    mov %rdx, %rax",
        "    mov $1000000, %r10",
        "    imul %r10, %rax",
        "    mov %rax, -8(%rbp)",
        "    mov $35, %rax",
        "    lea -16(%rbp), %rdi",
        "    xor %esi, %esi",
        "    syscall",
        "    mov %rbp, %rsp",
        "    pop %rbp",
        "    ret",
        "y_heap_used:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    mov $12, %rax",
        "    xor %edi, %edi",
        "    syscall",
        "    pop %rbp",
        "    ret",
        "y_range:",        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r12",
        "    push %r13",
        "    mov 16(%rbp), %rbx",
        "    test %rbx, %rbx",
        "    jns yrg_ok",
        "    xor %ebx, %ebx",
        "yrg_ok:",
        "    mov %rbx, %rdi",
        "    shl $3, %rdi",
        "    add $16, %rdi",
        "    call y_alloc",
        "    mov %rax, %r12",
        "    mov %rbx, (%r12)",
        "    mov %rbx, 8(%r12)",
        "    xor %r13d, %r13d",
        "yrg_loop:",
        "    cmp %rbx, %r13",
        "    jge yrg_done",
        "    mov %r13, 16(%r12,%r13,8)",
        "    inc %r13",
        "    jmp yrg_loop",
        "yrg_done:",
        "    mov %r12, %rax",
        "    pop %r13",
        "    pop %r12",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_arr_slice:",        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r12",
        "    push %r13",
        "    push %r14",
        "    push %r15",
        "    mov 40(%rbp), %rbx",
        "    mov 32(%rbp), %r12",
        "    mov 24(%rbp), %r13",
        "    mov 16(%rbp), %r9",
        "    mov (%rbx), %r15",
        "    test %r12, %r12",
        "    jns yas_lo1",
        "    xor %r12d, %r12d",
        "yas_lo1:",
        "    cmp %r15, %r12",
        "    jle yas_lo2",
        "    mov %r15, %r12",
        "yas_lo2:",
        "    test %r13, %r13",
        "    jns yas_hi1",
        "    xor %r13d, %r13d",
        "yas_hi1:",
        "    cmp %r15, %r13",
        "    jle yas_hi2",
        "    mov %r15, %r13",
        "yas_hi2:",
        "    mov %r13, %r14",
        "    sub %r12, %r14",
        "    test %r14, %r14",
        "    jns yas_n",
        "    xor %r14d, %r14d",
        "yas_n:",
        "    mov %r14, %rdi",
        "    imul %r9, %rdi",
        "    add $16, %rdi",
        "    push %r9",
        "    call y_alloc",
        "    pop %r9",
        "    mov %rax, %r15",
        "    mov %r14, (%r15)",
        "    mov %r14, 8(%r15)",
        "    xor %edx, %edx",
        "yas_copy:",
        "    cmp %r14, %rdx",
        "    jge yas_done",
        "    mov %r12, %rax",
        "    add %rdx, %rax",
        "    imul %r9, %rax",
        "    add %rbx, %rax",
        "    mov %rdx, %rsi",
        "    imul %r9, %rsi",
        "    add %r15, %rsi",
        "    cmp $1, %r9",
        "    je yas_cp1",
        "    mov 16(%rax), %rcx",
        "    mov %rcx, 16(%rsi)",
        "    jmp yas_cpn",
        "yas_cp1:",
        "    movzbq 16(%rax), %rcx",
        "    movb %cl, 16(%rsi)",
        "yas_cpn:",
        "    inc %rdx",
        "    jmp yas_copy",
        "yas_done:",
        "    mov %r15, %rax",
        "    pop %r15",
        "    pop %r14",
        "    pop %r13",
        "    pop %r12",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_arr_eq:",        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r12",
        "    mov 32(%rbp), %rbx",
        "    mov 24(%rbp), %r12",
        "    mov 16(%rbp), %r9",
        "    mov (%rbx), %rcx",
        "    mov (%r12), %rdx",
        "    cmp %rdx, %rcx",
        "    jnz yae_ne",
        "    xor %edx, %edx",
        "yae_loop:",
        "    cmp %rcx, %rdx",
        "    jge yae_eq",
        "    mov %rdx, %rax",
        "    imul %r9, %rax",
        "    mov %rax, %rsi",
        "    add %rbx, %rax",
        "    add %r12, %rsi",
        "    cmp $1, %r9",
        "    je yae_c1",
        "    mov 16(%rax), %rax",
        "    mov 16(%rsi), %rsi",
        "    jmp yae_cn",
        "yae_c1:",
        "    movzbq 16(%rax), %rax",
        "    movzbq 16(%rsi), %rsi",
        "yae_cn:",
        "    cmp %rsi, %rax",
        "    jnz yae_ne",
        "    inc %rdx",
        "    jmp yae_loop",
        "yae_eq:",
        "    mov $1, %rax",
        "    jmp yae_done",
        "yae_ne:",
        "    xor %eax, %eax",
        "yae_done:",
        "    pop %r12",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_arr_eq_str:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r12",
        "    push %r13",
        "    push %r14",
        "    mov 24(%rbp), %rbx",
        "    mov 16(%rbp), %r12",
        "    mov (%rbx), %r13",
        "    mov (%r12), %rdx",
        "    cmp %rdx, %r13",
        "    jnz yaes_ne",
        "    xor %r14d, %r14d",
        "yaes_loop:",
        "    cmp %r13, %r14",
        "    jge yaes_eq",
        "    mov 16(%rbx,%r14,8), %rax",
        "    push %rax",
        "    mov 16(%r12,%r14,8), %rax",
        "    push %rax",
        "    call y_str_eq",
        "    add $16, %rsp",
        "    test %rax, %rax",
        "    jz yaes_ne",
        "    inc %r14",
        "    jmp yaes_loop",
        "yaes_eq:",
        "    mov $1, %rax",
        "    jmp yaes_done",
        "yaes_ne:",
        "    xor %eax, %eax",
        "yaes_done:",
        "    pop %r14",
        "    pop %r13",
        "    pop %r12",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_float_tostr:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r12",
        "    push %r13",
        "    mov 16(%rbp), %rax",
        "    movq %rax, %xmm0",
        "    xor %r13d, %r13d",
        "    xor %ecx, %ecx",
        "    movq %rcx, %xmm2",
        "    ucomisd %xmm2, %xmm0",
        "    setb %al",
        "    movzbq %al, %rax",
        "    test %rax, %rax",
        "    jz yft_pos",
        "    mov $1, %r13",
        "    xor %ecx, %ecx",
        "    movq %rcx, %xmm2",
        "    subsd %xmm0, %xmm2",
        "    movq %xmm2, %rax",
        "    movq %rax, %xmm0",
        "yft_pos:",
        "    mov $1, %rcx",
        "    shl $62, %rcx",
        "    cvtsi2sd %rcx, %xmm2",
        "    addsd %xmm2, %xmm2",
        "    ucomisd %xmm2, %xmm0",
        "    setae %al",
        "    movzbq %al, %rax",
        "    test %rax, %rax",
        "    jz yft_small",
        "    lea ystr_bigflt_h(%rip), %rax",
        "    jmp yft_ret",
        "yft_small:",
        "    cvttsd2si %xmm0, %rbx",
        "    cvtsi2sd %rbx, %xmm1",
        "    subsd %xmm1, %xmm0",
        "    mov $1000000, %rcx",
        "    cvtsi2sd %rcx, %xmm1",
        "    mulsd %xmm1, %xmm0",
        "    mov $1, %rcx",
        "    cvtsi2sd %rcx, %xmm1",
        "    mov $2, %rcx",
        "    cvtsi2sd %rcx, %xmm2",
        "    divsd %xmm2, %xmm1",
        "    addsd %xmm1, %xmm0",
        "    cvttsd2si %xmm0, %r12",
        "    mov $1000000, %rcx",
        "    cmp %rcx, %r12",
        "    jl yft_fr",
        "    xor %r12d, %r12d",
        "    inc %rbx",
        "yft_fr:",
        "    push %rbx",
        "    call y_long_tostr",
        "    add $8, %rsp",
        "    mov %rax, %rbx",
        "    test %r13, %r13",
        "    jz yft_nosign",
        "    lea ystr_minus_h(%rip), %rax",
        "    push %rax",
        "    push %rbx",
        "    call y_str_cat",
        "    add $16, %rsp",
        "    mov %rax, %rbx",
        "yft_nosign:",
        "    lea ystr_dot_h(%rip), %rax",
        "    push %rbx",
        "    push %rax",
        "    call y_str_cat",
        "    add $16, %rsp",
        "    mov %rax, %rbx",
        "    mov $1000000, %rcx",
        "    add %r12, %rcx",
        "    push %rcx",
        "    call y_long_tostr",
        "    add $8, %rsp",
        "    push %rax",
        "    mov $1, %rax",
        "    push %rax",
        "    mov $6, %rax",
        "    push %rax",
        "    call y_str_substr",
        "    add $24, %rsp",
        "    push %rbx",
        "    push %rax",
        "    call y_str_cat",
        "    add $16, %rsp",
        "yft_ret:",
        "    pop %r13",
        "    pop %r12",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_print_float:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rdi",
        "    call y_float_tostr",
        "    add $8, %rsp",
        "    mov %rax, %rdi",
        "    call y_print_hstr",
        "    pop %rbp",
        "    ret",
        "y_str_substr:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r12",
        "    push %r13",
        "    push %r14",
        "    mov 32(%rbp), %rbx",
        "    mov 24(%rbp), %r13",
        "    mov 16(%rbp), %r14",
        "    mov (%rbx), %rcx",
        "    mov %r13, %rax",
        "    cmp $0, %rax",
        "    jge ysb_stok",
        "    xor %eax, %eax",
        "ysb_stok:",
        "    cmp %rcx, %rax",
        "    jge ysb_empty",
        "    mov %rcx, %rdx",
        "    sub %rax, %rdx",
        "    cmp %r14, %rdx",
        "    jge ysb_cntok",
        "    mov %rdx, %r14",
        "    jmp ysb_cntok2",
        "ysb_cntok:",
        "    cmp $0, %r14",
        "    jge ysb_cntok2",
        "    mov %rdx, %r14",
        "ysb_cntok2:",
        "    mov %r14, %rcx",
        "    mov %r14, %rdi",
        "    add $16, %rdi",
        "    mov %rax, %r12",
        "    call y_alloc",
        "    mov %rax, %r13",
        "    mov %r13, %rdi",
        "    add $8, %rdi",
        "    mov %rbx, %rsi",
        "    add $8, %rsi",
        "    add %r12, %rsi",
        "    mov %r14, %rcx",
        "    test %rcx, %rcx",
        "    jz ysb_nocopy",
        "    push %r13",
        "    push %r14",
        "    call ysc_copy",
        "    pop %r14",
        "    pop %r13",
        "ysb_nocopy:",
        "    mov %r14, (%r13)",
        "    movb $0, 8(%r13,%r14,1)",
        "    mov %r13, %rax",
        "    jmp ysb_done",
        "ysb_empty:",
        "    mov $16, %rdi",
        "    call y_alloc",
        "    mov $0, (%rax)",
        "    movb $0, 8(%rax)",
        "ysb_done:",
        "    pop %r14",
        "    pop %r13",
        "    pop %r12",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_str_trim:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    mov 16(%rbp), %rbx",
        "    mov (%rbx), %rcx",
        "    mov %rbx, %rbx",
        "    add $8, %rbx",
        "    xor %r13d, %r13d",
        "yst_lead:",
        "    cmp %rcx, %r13",
        "    jge yst_rstart",
        "    movzbq (%rbx,%r13,1), %rax",
        "    cmp $32, %rax",
        "    jz yst_leadnx",
        "    cmp $9, %rax",
        "    jz yst_leadnx",
        "    cmp $10, %rax",
        "    jz yst_leadnx",
        "    cmp $13, %rax",
        "    jz yst_leadnx",
        "    jmp yst_rstart",
        "yst_leadnx:",
        "    inc %r13",
        "    jmp yst_lead",
        "yst_rstart:",
        "    mov %rcx, %rdx",
        "yst_trail:",
        "    cmp %r13, %rdx",
        "    jle yst_slice",
        "    mov %rdx, %rax",
        "    dec %rax",
        "    movzbq (%rbx,%rax,1), %rax",
        "    cmp $32, %rax",
        "    jz yst_tr",
        "    cmp $9, %rax",
        "    jz yst_tr",
        "    cmp $10, %rax",
        "    jz yst_tr",
        "    cmp $13, %rax",
        "    jz yst_tr",
        "    jmp yst_slice",
        "yst_tr:",
        "    dec %rdx",
        "    jmp yst_trail",
        "yst_slice:",
        "    mov %rdx, %rcx",
        "    sub %r13, %rcx",
        "    mov %rcx, %rdi",
        "    add $16, %rdi",
        "    push %rbx",
        "    push %r13",
        "    push %rcx",
        "    call y_alloc",
        "    pop %rcx",
        "    pop %r13",
        "    pop %rbx",
        "    mov %rax, %r14",
        "    mov %rbx, %rsi",
        "    add %r13, %rsi",
        "    mov %r14, %rdi",
        "    add $8, %rdi",
        "    push %r14",
        "    push %rcx",
        "    call ysc_copy",
        "    pop %rcx",
        "    pop %r14",
        "    mov %rcx, (%r14)",
        "    movb $0, 8(%r14,%rcx,1)",
        "    mov %r14, %rax",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_str_ord:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    mov 16(%rbp), %rax",
        "    mov (%rax), %rcx",
        "    cmp $0, %rcx",
        "    jle yso_empty",
        "    movzbq 8(%rax), %rax",
        "    jmp yso_done",
        "yso_empty:",
        "    mov $-1, %rax",
        "yso_done:",
        "    pop %rbp",
        "    ret",
        "y_str_chr:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    mov 16(%rbp), %rbx",
        "    mov $17, %rdi",
        "    call y_alloc",
        "    mov %rax, %r13",
        "    mov $1, (%r13)",
        "    movb %bl, 8(%r13)",
        "    movb $0, 9(%r13)",
        "    mov %r13, %rax",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_str_tonum:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    mov 16(%rbp), %rbx",
        "    mov (%rbx), %rcx",
        "    mov %rbx, %rbx",
        "    add $8, %rbx",
        "    xor %eax, %eax",
        "    xor %r13d, %r13d",
        "    test %rcx, %rcx",
        "    jz ytn_done",
        "    movzbq (%rbx), %r13",
        "    cmp $45, %r13",
        "    jnz ytn_digits",
        "    xor %r13d, %r13d",
        "    mov $1, %rdx",
        "    mov $1, %r13",
        "    jmp ytn_loop",
        "ytn_digits:",
        "    xor %r13d, %r13d",
        "    xor %edx, %edx",
        "ytn_loop:",
        "    cmp %rcx, %r13",
        "    jge ytn_sign",
        "    movzbq (%rbx,%r13,1), %rdi",
        "    cmp $48, %rdi",
        "    jl ytn_stop",
        "    cmp $57, %rdi",
        "    jg ytn_stop",
        "    mov $10, %rsi",
        "    imul %rsi, %rax",
        "    sub $48, %rdi",
        "    add %rdi, %rax",
        "    inc %r13",
        "    jmp ytn_loop",
        "ytn_stop:",
        "    mov %r13, %rcx",
        "ytn_sign:",
        "    test %rdx, %rdx",
        "    jz ytn_done",
        "    neg %rax",
        "ytn_done:",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_long_tostr:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    mov 16(%rbp), %rbx",
        "    mov %rbx, %rax",
        "    cmp $0, %rax",
        "    jge ylt_pos",
        "    neg %rax",
        "    mov $1, %r13",
        "    jmp ylt_count",
        "ylt_pos:",
        "    xor %r13d, %r13d",
        "ylt_count:",
        "    mov %rax, %r14",
        "    mov $1, %rcx",
        "    mov $10, %rdi",
        "ylt_cloop:",
        "    cmp $10, %r14",
        "    jl ylt_cdone",
        "    mov %r14, %rax",
        "    xor %edx, %edx",
        "    div %rdi",
        "    mov %rax, %r14",
        "    inc %rcx",
        "    jmp ylt_cloop",
        "ylt_cdone:",
        "    add %r13, %rcx",
        "    mov %rcx, %r14",
        "    mov %rcx, %rdi",
        "    add $16, %rdi",
        "    push %r13",
        "    push %r14",
        "    push %rbx",
        "    call y_alloc",
        "    pop %rbx",
        "    pop %r14",
        "    pop %r13",
        "    mov %rax, %rdi",
        "    mov %rbx, %rax",
        "    cmp $0, %rax",
        "    jge ylt_fill",
        "    movb $45, 8(%rdi)",
        "    neg %rax",
        "ylt_fill:",
        "    mov %r14, %rcx",
        "    sub %r13, %rcx",
        "    dec %rcx",
        "    add %r13, %rcx",
        "    mov $10, %rsi",
        "ylt_floop:",
        "    xor %edx, %edx",
        "    div %rsi",
        "    add $48, %rdx",
        "    movb %dl, 8(%rdi,%rcx,1)",
        "    dec %rcx",
        "    test %rax, %rax",
        "    jnz ylt_floop",
        "    mov %r14, (%rdi)",
        "    movb $0, 8(%rdi,%r14,1)",
        "    mov %rdi, %rax",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_bool_tostr:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    mov 16(%rbp), %rax",
        "    test %rax, %rax",
        "    jz ybt_f",
        "    lea ystr_true_h(%rip), %rax",
        "    jmp ybt_done",
        "ybt_f:",
        "    lea ystr_false_h(%rip), %rax",
        "ybt_done:",
        "    pop %rbp",
        "    ret",
        "y_str_index:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    mov 24(%rbp), %rbx",
        "    mov 16(%rbp), %r13",
        "    mov (%rbx), %rcx",
        "    mov (%r13), %rdx",
        "    cmp $0, %rdx",
        "    jz ysi_no",
        "    cmp %rdx, %rcx",
        "    jl ysi_no",
        "    mov %rbx, %rbx",
        "    add $8, %rbx",
        "    mov %r13, %r13",
        "    add $8, %r13",
        "    xor %eax, %eax",
        "ysi_outer:",
        "    mov %rcx, %rdi",
        "    sub %rax, %rdi",
        "    cmp %rdx, %rdi",
        "    jl ysi_no",
        "    xor %r14d, %r14d",
        "ysi_inner:",
        "    cmp %rdx, %r14",
        "    jge ysi_found",
        "    mov %rax, %rdi",
        "    add %r14, %rdi",
        "    movzbq (%rbx,%rdi,1), %rdi",
        "    movzbq (%r13,%r14,1), %rsi",
        "    cmp %rsi, %rdi",
        "    jnz ysi_next",
        "    inc %r14",
        "    jmp ysi_inner",
        "ysi_next:",
        "    inc %rax",
        "    jmp ysi_outer",
        "ysi_found:",
        "    jmp ysi_done",
        "ysi_no:",
        "    mov $-1, %rax",
        "ysi_done:",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_str_lastidx:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    mov 24(%rbp), %rbx",
        "    mov 16(%rbp), %r13",
        "    mov (%rbx), %rcx",
        "    mov (%r13), %rdx",
        "    cmp $0, %rdx",
        "    jz ysl_no",
        "    cmp %rdx, %rcx",
        "    jl ysl_no",
        "    mov %rbx, %rbx",
        "    add $8, %rbx",
        "    mov %r13, %r13",
        "    add $8, %r13",
        "    mov %rcx, %rax",
        "    sub %rdx, %rax",
        "ysl_outer:",
        "    cmp $0, %rax",
        "    jl ysl_no",
        "    xor %r14d, %r14d",
        "ysl_inner:",
        "    cmp %rdx, %r14",
        "    jge ysl_done",
        "    mov %rax, %rdi",
        "    add %r14, %rdi",
        "    movzbq (%rbx,%rdi,1), %rdi",
        "    movzbq (%r13,%r14,1), %rsi",
        "    cmp %rsi, %rdi",
        "    jnz ysl_next",
        "    inc %r14",
        "    jmp ysl_inner",
        "ysl_next:",
        "    dec %rax",
        "    jmp ysl_outer",
        "ysl_no:",
        "    mov $-1, %rax",
        "ysl_done:",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_str_join:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    push %r15",
        "    mov 24(%rbp), %rbx",
        "    mov 16(%rbp), %r13",
        "    mov (%rbx), %r14",
        "    mov (%r13), %rcx",
        "    test %r14, %r14",
        "    jz ysj_empty",
        "    xor %r15d, %r15d",
        "    xor %eax, %eax",
        "ysj_len:",
        "    cmp %r14, %r15",
        "    jge ysj_mk",
        "    mov 16(%rbx,%r15,8), %rdi",
        "    mov (%rdi), %rdi",
        "    add %rdi, %rax",
        "    inc %r15",
        "    jmp ysj_len",
        "ysj_mk:",
        "    mov %rcx, %r15",
        "    imul %r14, %r15",
        "    sub %rcx, %r15",
        "    add %r15, %rax",
        "    mov %rax, %r14",
        "    mov %rax, %rdi",
        "    add $16, %rdi",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    call y_alloc",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    mov %rax, %r15",
        "    mov %r15, %rdi",
        "    add $8, %rdi",
        "    xor %r10d, %r10d",
        "ysj_fill:",
        "    mov (%rbx), %rax",
        "    cmp %r10, %rax",
        "    jle ysj_fin",
        "    mov 16(%rbx,%r10,8), %rsi",
        "    mov (%rsi), %rcx",
        "    add $8, %rsi",
        "    push %rdi",
        "    push %rsi",
        "    push %rcx",
        "    push %r10",
        "    push %r13",
        "    push %r14",
        "    push %r15",
        "    push %rbx",
        "    call ysc_copy",
        "    pop %rbx",
        "    pop %r15",
        "    pop %r14",
        "    pop %r13",
        "    pop %r10",
        "    pop %rcx",
        "    pop %rsi",
        "    pop %rdi",
        "    add %rcx, %rdi",
        "    mov (%rbx), %rax",
        "    dec %rax",
        "    cmp %r10, %rax",
        "    jle ysj_nodel",
        "    mov (%r13), %rcx",
        "    mov %r13, %rsi",
        "    add $8, %rsi",
        "    push %rdi",
        "    push %rsi",
        "    push %rcx",
        "    push %r10",
        "    push %r13",
        "    push %r14",
        "    push %r15",
        "    push %rbx",
        "    call ysc_copy",
        "    pop %rbx",
        "    pop %r15",
        "    pop %r14",
        "    pop %r13",
        "    pop %r10",
        "    pop %rcx",
        "    pop %rsi",
        "    pop %rdi",
        "    add %rcx, %rdi",
        "ysj_nodel:",
        "    inc %r10",
        "    jmp ysj_fill",
        "ysj_fin:",
        "    mov %r14, (%r15)",
        "    movb $0, 8(%r15,%r14,1)",
        "    mov %r15, %rax",
        "    jmp ysj_done",
        "ysj_empty:",
        "    mov $16, %rdi",
        "    call y_alloc",
        "    mov $0, (%rax)",
        "    movb $0, 8(%rax)",
        "ysj_done:",
        "    pop %r15",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_str_split:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r12",
        "    push %r13",
        "    push %r14",
        "    push %r15",
        "    push %r10",
        "    push %r11",
        "    mov 24(%rbp), %rbx",
        "    mov 16(%rbp), %r13",
        "    mov (%rbx), %r14",
        "    mov (%r13), %r10",
        "    test %r10, %r10",
        "    jz yss_empty",
        "    mov %rbx, %rbx",
        "    add $8, %rbx",
        "    mov %r13, %r13",
        "    add $8, %r13",
        "    mov %r10, %r11",
        "    xor %r15d, %r15d",
        "    xor %eax, %eax",
        "yss_count:",
        "    cmp %r14, %rax",
        "    jge yss_mk",
        "    inc %r15",
        "    mov %rax, %rdi",
        "    jmp yss_adv",
        "yss_adv:",
        "    mov %r14, %rdx",
        "    sub %rax, %rdx",
        "    cmp %r11, %rdx",
        "    jl yss_noskip",
        "    push %rax",
        "    push %r10",
        "    push %r11",
        "    push %r14",
        "    push %r15",
        "    push %rbx",
        "    push %r13",
        "    call yss_ismatch",
        "    mov %rax, %rcx",
        "    pop %r13",
        "    pop %rbx",
        "    pop %r15",
        "    pop %r14",
        "    pop %r11",
        "    pop %r10",
        "    pop %rax",
        "    test %rcx, %rcx",
        "    jz yss_noskip",
        "    add %r11, %rax",
        "    jmp yss_count",
        "yss_noskip:",
        "    inc %rax",
        "    jmp yss_count",
        "yss_mk:",
        "    mov %r15, %rcx",
        "    shl $3, %rcx",
        "    add $16, %rcx",
        "    mov %rcx, %rdi",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    push %r15",
        "    push %r10",
        "    push %r11",
        "    call y_alloc",
        "    pop %r11",
        "    pop %r10",
        "    pop %r15",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    mov %rax, %r12",
        "    mov %rax, %rdi",
        "    mov %r15, (%rdi)",
        "    mov %r15, 8(%rdi)",
        "    xor %r15d, %r15d",
        "    xor %eax, %eax",
        "    xor %r10d, %r10d",
        "yss_fill:",
        "    cmp %r14, %rax",
        "    jge yss_fin",
        "    jmp yss_fscan",
        "yss_fscan:",
        "    mov %r14, %rcx",
        "    sub %rax, %rcx",
        "    cmp %r11, %rcx",
        "    jl yss_fin",
        "    push %rax",
        "    push %rdi",
        "    push %r10",
        "    push %r11",
        "    push %r14",
        "    push %r15",
        "    push %rbx",
        "    push %r13",
        "    call yss_ismatch",
        "    mov %rax, %rcx",
        "    pop %r13",
        "    pop %rbx",
        "    pop %r15",
        "    pop %r14",
        "    pop %r11",
        "    pop %r10",
        "    pop %rdi",
        "    pop %rax",
        "    test %rcx, %rcx",
        "    jz yss_fnext",
        "    mov %rax, %rdx",
        "    sub %r10, %rdx",
        "    mov %rdx, %rcx",
        "    mov %rcx, %rdi",
        "    add $16, %rdi",
        "    push %rax",
        "    push %rdi",
        "    push %r10",
        "    push %rdx",
        "    push %r11",
        "    push %r14",
        "    push %r15",
        "    push %rbx",
        "    push %r13",
        "    call y_alloc",
        "    mov %rax, %rsi",
        "    pop %r13",
        "    pop %rbx",
        "    pop %r15",
        "    pop %r14",
        "    pop %r11",
        "    pop %rdx",
        "    pop %r10",
        "    pop %rdi",
        "    pop %rax",
        "    mov %rdx, (%rsi)",
        "    mov %rsi, %rdi",
        "    add $8, %rdi",
        "    push %rax",
        "    mov %r10, %rax",
        "    add %rbx, %rax",
        "    mov %rsi, %r9",
        "    mov %rax, %rsi",
        "    mov %rdx, %rcx",
        "    push %rax",
        "    push %rdi",
        "    push %rsi",
        "    push %rdx",
        "    push %r14",
        "    push %r15",
        "    push %rbx",
        "    push %r13",
        "    push %r10",
        "    push %r11",
        "    call ysc_copy",
        "    pop %r11",
        "    pop %r10",
        "    pop %r13",
        "    pop %rbx",
        "    pop %r15",
        "    pop %r14",
        "    pop %rdx",
        "    pop %rsi",
        "    pop %rdi",
        "    pop %rax",
        "    movb $0, 8(%r9,%rdx,1)",
        "    mov %r9, 16(%r12,%r15,8)",
        "    inc %r15",
        "    pop %rax",
        "    add %r11, %rax",
        "    mov %rax, %r10",
        "    jmp yss_fill",
        "yss_fpiece:",
        "    mov %r14, %rdx",
        "    sub %rax, %rdx",
        "    mov %rdx, %rcx",
        "    mov %rcx, %rdi",
        "    add $16, %rdi",
        "    push %rax",
        "    push %rdi",
        "    push %r10",
        "    push %rdx",
        "    push %r11",
        "    push %r14",
        "    push %r15",
        "    push %rbx",
        "    push %r13",
        "    call y_alloc",
        "    mov %rax, %rsi",
        "    pop %r13",
        "    pop %rbx",
        "    pop %r15",
        "    pop %r14",
        "    pop %r11",
        "    pop %rdx",
        "    pop %r10",
        "    pop %rdi",
        "    pop %rax",
        "    mov %rdx, (%rsi)",
        "    mov %rsi, %rdi",
        "    add $8, %rdi",
        "    push %rax",
        "    mov %r10, %rax",
        "    add %rbx, %rax",
        "    mov %rsi, %r9",
        "    mov %rax, %rsi",
        "    mov %rdx, %rcx",
        "    push %rax",
        "    push %rdi",
        "    push %rsi",
        "    push %rdx",
        "    push %r14",
        "    push %r15",
        "    push %rbx",
        "    push %r13",
        "    push %r10",
        "    push %r11",
        "    call ysc_copy",
        "    pop %r11",
        "    pop %r10",
        "    pop %r13",
        "    pop %rbx",
        "    pop %r15",
        "    pop %r14",
        "    pop %rdx",
        "    pop %rsi",
        "    pop %rdi",
        "    pop %rax",
        "    movb $0, 8(%r9,%rdx,1)",
        "    mov %r9, 16(%r12,%r15,8)",
        "    inc %r15",
        "    jmp yss_fin",
        "yss_fnext:",
        "    inc %rax",
        "    jmp yss_fill",
        "yss_fin:",
        "    mov %r14, %rdx",
        "    sub %r10, %rdx",
        "    cmp $0, %rdx",
        "    jle yss_fin_ret",
        "    mov %rdx, %rcx",
        "    mov %rcx, %rdi",
        "    add $16, %rdi",
        "    push %rax",
        "    push %rdi",
        "    push %r10",
        "    push %rdx",
        "    push %r11",
        "    push %r14",
        "    push %r15",
        "    push %rbx",
        "    push %r13",
        "    call y_alloc",
        "    mov %rax, %rsi",
        "    pop %r13",
        "    pop %rbx",
        "    pop %r15",
        "    pop %r14",
        "    pop %r11",
        "    pop %rdx",
        "    pop %r10",
        "    pop %rdi",
        "    pop %rax",
        "    mov %rdx, (%rsi)",
        "    mov %rsi, %rdi",
        "    add $8, %rdi",
        "    push %rax",
        "    mov %r10, %rax",
        "    add %rbx, %rax",
        "    mov %rsi, %r9",
        "    mov %rax, %rsi",
        "    mov %rdx, %rcx",
        "    push %rax",
        "    push %rdi",
        "    push %rsi",
        "    push %rdx",
        "    push %r14",
        "    push %r15",
        "    push %rbx",
        "    push %r13",
        "    push %r10",
        "    push %r11",
        "    call ysc_copy",
        "    pop %r11",
        "    pop %r10",
        "    pop %r13",
        "    pop %rbx",
        "    pop %r15",
        "    pop %r14",
        "    pop %rdx",
        "    pop %rsi",
        "    pop %rdi",
        "    pop %rax",
        "    movb $0, 8(%r9,%rdx,1)",
        "    mov %r9, 16(%r12,%r15,8)",
        "    inc %r15",
        "    add $8, %rsp",
        "yss_fin_ret:",
        "    mov %r12, %rax",
        "    mov %r15, (%rax)",
        "    jmp yss_done",
        "yss_empty:",
        "    mov $16, %rdi",
        "    call y_alloc",
        "    mov $0, (%rax)",
        "    mov $0, 8(%rax)",
        "yss_done:",
        "    pop %r11",
        "    pop %r10",
        "    pop %r15",
        "    pop %r14",
        "    pop %r13",
        "    pop %r12",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "yss_ismatch:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    push %rsi",
        "    push %rdi",
        "    mov %rax, %rdi",
        "    xor %eax, %eax",
        "yssm_loop:",
        "    cmp %r11, %rax",
        "    jge yssm_yes",
        "    mov %rdi, %rcx",
        "    add %rax, %rcx",
        "    movzbq (%rbx,%rcx,1), %rcx",
        "    movzbq (%r13,%rax,1), %rdx",
        "    cmp %rdx, %rcx",
        "    jnz yssm_no",
        "    inc %rax",
        "    jmp yssm_loop",
        "yssm_yes:",
        "    mov $1, %rax",
        "    jmp yssm_done",
        "yssm_no:",
        "    xor %eax, %eax",
        "yssm_done:",
        "    pop %rdi",
        "    pop %rsi",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_arr_push:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r12",
        "    push %r13",
        "    push %r14",
        "    push %r15",
        "    mov 32(%rbp), %rbx",
        "    mov 24(%rbp), %r12",
        "    mov 16(%rbp), %r9",
        "    mov (%rbx), %rcx",
        "    mov 8(%rbx), %rdx",
        "    cmp %rdx, %rcx",
        "    jz yap_grow",
        "    mov %rcx, %r13",
        "    imul %r9, %r13",
        "    add $16, %r13",
        "    add %rbx, %r13",
        "    cmp $1, %r9",
        "    je yap_st1",
        "    mov %r12, (%r13)",
        "    jmp yap_stn",
        "yap_st1:",
        "    mov %r12, %rdx",
        "    movb %dl, (%r13)",
        "yap_stn:",
        "    inc %rcx",
        "    mov %rcx, (%rbx)",
        "    mov %rbx, %rax",
        "    jmp yap_done",
        "yap_grow:",
        "    mov %rdx, %r13",
        "    shl $1, %r13",
        "    add $8, %r13",
        "    mov %r13, %rdi",
        "    imul %r9, %rdi",
        "    add $16, %rdi",
        "    push %rcx",
        "    push %rdx",
        "    push %r9",
        "    call y_alloc",
        "    pop %r9",
        "    pop %rdx",
        "    pop %rcx",
        "    mov %rcx, (%rax)",
        "    mov %r13, 8(%rax)",
        "    mov %rax, %r13",
        "    xor %r14d, %r14d",
        "yap_copy:",
        "    cmp %rcx, %r14",
        "    jge yap_copy_done",
        "    mov %r14, %rax",
        "    imul %r9, %rax",
        "    add %rbx, %rax",
        "    mov %r14, %rsi",
        "    imul %r9, %rsi",
        "    add %r13, %rsi",
        "    cmp $1, %r9",
        "    je yap_cp1",
        "    mov 16(%rax), %r15",
        "    mov %r15, 16(%rsi)",
        "    jmp yap_cpn",
        "yap_cp1:",
        "    movzbq 16(%rax), %r15",
        "    mov %r15, %rdx",
        "    movb %dl, 16(%rsi)",
        "yap_cpn:",
        "    inc %r14",
        "    jmp yap_copy",
        "yap_copy_done:",
        "    mov %rcx, %rax",
        "    imul %r9, %rax",
        "    add $16, %rax",
        "    add %r13, %rax",
        "    cmp $1, %r9",
        "    je yap_last1",
        "    mov %r12, (%rax)",
        "    jmp yap_lastn",
        "yap_last1:",
        "    mov %r12, %rdx",
        "    movb %dl, (%rax)",
        "yap_lastn:",
        "    inc %rcx",
        "    mov %rcx, (%r13)",
        "    mov %r13, %rax",
        "yap_done:",
        "    pop %r15",
        "    pop %r14",
        "    pop %r13",
        "    pop %r12",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_arr_clone:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r12",
        "    push %r13",
        "    push %r14",
        "    mov %rdi, %rbx",
        "    mov (%rbx), %r12",
        "    mov %r12, %rdi",
        "    shl $3, %rdi",
        "    add $16, %rdi",
        "    call y_alloc",
        "    mov (%rbx), %r12",
        "    mov %r12, (%rax)",
        "    mov %r12, 8(%rax)",
        "    xor %r13d, %r13d",
        "yacl_loop:",
        "    cmp %r12, %r13",
        "    jge yacl_done",
        "    mov 16(%rbx,%r13,8), %r14",
        "    mov %r14, 16(%rax,%r13,8)",
        "    inc %r13",
        "    jmp yacl_loop",
        "yacl_done:",
        "    pop %r14",
        "    pop %r13",
        "    pop %r12",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_rec_clone:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r12",
        "    push %r13",
        "    push %r14",
        "    mov %rdi, %rbx",
        "    mov -8(%rbx), %r12",
        "    mov 8(%r12), %r13",
        "    mov %r13, %rdi",
        "    shl $3, %rdi",
        "    add $16, %rdi",
        "    call y_alloc",
        "    mov 8(%r12), %r13",
        "    mov %r12, (%rax)",
        "    xor %r8d, %r8d",
        "yrcl_loop:",
        "    cmp %r13, %r8",
        "    jge yrcl_done",
        "    mov (%rbx,%r8,8), %r9",
        "    mov %r9, 8(%rax,%r8,8)",
        "    inc %r8",
        "    jmp yrcl_loop",
        "yrcl_done:",
        "    add $8, %rax",
        "    pop %r14",
        "    pop %r13",
        "    pop %r12",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_argv_init:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    push %r15",
        "    mov 24(%rbp), %rbx",
        "    mov 16(%rbp), %r13",
        "    mov %r13, %rax",
        "    shl $3, %rax",
        "    add $16, %rax",
        "    mov %rax, %rdi",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    call y_alloc",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    mov %rax, %r15",
        "    mov %r13, (%r15)",
        "    mov %r13, 8(%r15)",
        "    xor %r14d, %r14d",
        "yai_loop:",
        "    cmp %r13, %r14",
        "    jge yai_done",
        "    mov (%rbx,%r14,8), %rcx",
        "    push %rcx",
        "    push %r13",
        "    push %r14",
        "    push %r15",
        "    push %rbx",
        "    mov %rcx, %rdi",
        "    call y_cstr_to_str",
        "    mov %rax, %rcx",
        "    pop %rbx",
        "    pop %r15",
        "    pop %r14",
        "    pop %r13",
        "    add $8, %rsp",
        "    mov %rcx, 16(%r15,%r14,8)",
        "    inc %r14",
        "    jmp yai_loop",
        "yai_done:",
        "    add $8, %rsp",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_argv:",
        "    mov %r15, %rax",
        "    ret",
        "y_cstr_to_str:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    mov %rdi, %rbx",
        "    xor %ecx, %ecx",
        "ycs_len:",
        "    movzbq (%rbx,%rcx,1), %rax",
        "    test %rax, %rax",
        "    jz ycs_mk",
        "    inc %rcx",
        "    jmp ycs_len",
        "ycs_mk:",
        "    mov %rcx, %r13",
        "    mov %rcx, %r14",
        "    mov %rcx, %rdi",
        "    add $16, %rdi",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    call y_alloc",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    mov %rax, %rdi",
        "    mov %r13, (%rdi)",
        "    mov %r14, %rcx",
        "    mov %rbx, %rsi",
        "    mov %rdi, %rax",
        "    add $8, %rax",
        "    mov %rax, %rdi",
        "    push %rdi",
        "    push %rsi",
        "    push %rcx",
        "    push %r13",
        "    push %r14",
        "    push %rbx",
        "    call ysc_copy",
        "    pop %rbx",
        "    pop %r14",
        "    pop %r13",
        "    pop %rcx",
        "    pop %rsi",
        "    pop %rdi",
        "    movb $0, 8(%rdi,%r13,1)",
        "    mov %rdi, %rax",
        "    sub $8, %rax",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_str_to_bytes:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    mov 16(%rbp), %rbx",
        "    mov (%rbx), %r13",
        "    mov %r13, %rdi",
        "    add $16, %rdi",
        "    call y_alloc",
        "    mov %rax, %r14",
        "    mov %r13, (%r14)",
        "    mov %r13, 8(%r14)",
        "    xor %r8d, %r8d",
        "ystb_loop:",
        "    cmp %r13, %r8",
        "    jge ystb_done",
        "    movzbq 8(%rbx,%r8,1), %rdx",
        "    movb %dl, 16(%r14,%r8,1)",
        "    inc %r8",
        "    jmp ystb_loop",
        "ystb_done:",
        "    mov %r14, %rax",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_bytes_to_str:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    mov 16(%rbp), %rbx",
        "    mov (%rbx), %r13",
        "    mov %r13, %rdi",
        "    add $16, %rdi",
        "    call y_alloc",
        "    mov %rax, %r14",
        "    mov %r13, (%r14)",
        "    xor %r8d, %r8d",
        "ybts_loop:",
        "    cmp %r13, %r8",
        "    jge ybts_done",
        "    movzbq 16(%rbx,%r8,1), %rdx",
        "    movb %dl, 8(%r14,%r8,1)",
        "    inc %r8",
        "    jmp ybts_loop",
        "ybts_done:",
        "    mov %r14, %rsi",
        "    add $8, %rsi",
        "    add %r13, %rsi",
        "    movb $0, (%rsi)",
        "    mov %r14, %rax",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_read_file:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    push %r15",
        "    mov 16(%rbp), %rbx",
        "    mov %rbx, %rax",
        "    add $8, %rax",
        "    mov %rax, %rsi",
        "    mov $-100, %rdi",
        "    mov $0, %rdx",
        "    mov $420, %r10",
        "    mov $257, %rax",
        "    syscall",
        "    cmp $0, %rax",
        "    jl yrf_fail",
        "    mov %rax, %r13",
        "    mov %r13, %rdi",
        "    xor %rsi, %rsi",
        "    mov $2, %rdx",
        "    mov $8, %rax",
        "    syscall",
        "    cmp $0, %rax",
        "    jl yrf_close_fail",
        "    mov %rax, %r15",
        "    mov %r13, %rdi",
        "    xor %rsi, %rsi",
        "    xor %rdx, %rdx",
        "    mov $8, %rax",
        "    syscall",
        "    mov %r15, %rdi",
        "    add $17, %rdi",
        "    push %r13",
        "    push %rbx",
        "    push %r15",
        "    call y_alloc",
        "    pop %r15",
        "    pop %rbx",
        "    pop %r13",
        "    mov %rax, %r14",
        "    mov %r13, %rdi",
        "    mov %r14, %rsi",
        "    add $8, %rsi",
        "    mov %r15, %rdx",
        "    xor %eax, %eax",
        "    syscall",
        "    cmp $0, %rax",
        "    jl yrf_close_fail2",
        "    mov %rax, %r15",
        "    mov %r13, %rdi",
        "    mov $3, %rax",
        "    syscall",
        "    mov %r15, (%r14)",
        "    movb $0, 8(%r14,%r15,1)",
        "    push %r14",
        "    mov $8, %rdi",
        "    call y_alloc",
        "    pop %rcx",
        "    mov %rcx, (%rax)",
        "    jmp yrf_done",
        "yrf_close_fail2:",
        "    mov %r13, %rdi",
        "    mov $3, %rax",
        "    syscall",
        "    xor %eax, %eax",
        "    jmp yrf_done",
        "yrf_close_fail:",
        "    mov %r13, %rdi",
        "    mov $3, %rax",
        "    syscall",
        "yrf_fail:",
        "    xor %eax, %eax",
        "yrf_done:",
        "    pop %r15",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_write_file:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r13",
        "    push %r14",
        "    mov 24(%rbp), %rbx",
        "    mov 16(%rbp), %r13",
        "    mov %rbx, %rax",
        "    add $8, %rax",
        "    mov %rax, %rsi",
        "    mov $-100, %rdi",
        "    mov $577, %rdx",
        "    mov $420, %r10",
        "    mov $257, %rax",
        "    syscall",
        "    cmp $0, %rax",
        "    jl ywf_fail",
        "    mov %rax, %r14",
        "    mov %r13, %rax",
        "    add $8, %rax",
        "    mov %rax, %rsi",
        "    mov (%r13), %rdx",
        "    mov %r14, %rdi",
        "    mov $1, %rax",
        "    syscall",
        "    mov %r14, %rdi",
        "    push %rax",
        "    mov $3, %rax",
        "    syscall",
        "    pop %rax",
        "    cmp $0, %rax",
        "    jl ywf_fail",
        "    mov $1, %rax",
        "    jmp ywf_done",
        "ywf_fail:",
        "    xor %eax, %eax",
        "ywf_done:",
        "    pop %r14",
        "    pop %r13",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
        "y_write_bytes:",
        "    push %rbp",
        "    mov %rsp, %rbp",
        "    push %rbx",
        "    push %r12",
        "    push %r13",
        "    push %r14",
        "    push %r15",
        "    mov 32(%rbp), %rbx",
        "    mov 24(%rbp), %r12",
        "    mov 16(%rbp), %r15",
        "    mov %rbx, %rax",
        "    add $8, %rax",
        "    mov %rax, %rsi",
        "    mov $-100, %rdi",
        "    mov $577, %rdx",
        "    mov $420, %r10",
        "    mov $257, %rax",
        "    syscall",
        "    cmp $0, %rax",
        "    jl ywb_fail",
        "    mov %rax, %r13",
        "    mov (%r12), %rax",
        "    mov %rax, %r14",
        "    mov %r14, %rdi",
        "    inc %rdi",
        "    call y_alloc",
        "    mov %rax, %r9",
        "    xor %r8d, %r8d",
        "ywb_pack:",
        "    cmp %r14, %r8",
        "    jge ywb_wstart",
        "    mov 16(%r12,%r8,8), %rcx",
        "    mov %r9, %rdi",
        "    add %r8, %rdi",
        "    mov %cl, (%rdi)",
        "    inc %r8",
        "    jmp ywb_pack",
        "ywb_wstart:",
        "    mov %r9, %rsi",
        "    mov %r14, %rdx",
        "    xor %ebx, %ebx",
        "ywb_loop:",
        "    test %rdx, %rdx",
        "    jz ywb_close",
        "    mov %r13, %rdi",
        "    mov $1, %rax",
        "    syscall",
        "    cmp $0, %rax",
        "    jle ywb_wfail",
        "    add %rax, %rsi",
        "    sub %rax, %rdx",
        "    add %rax, %rbx",
        "    jmp ywb_loop",
        "ywb_wfail:",
        "    mov %r13, %rdi",
        "    push %rax",
        "    mov $3, %rax",
        "    syscall",
        "    pop %rax",
        "    jmp ywb_fail",
        "ywb_close:",
        "    mov %r13, %rdi",
        "    push %rbx",
        "    mov $3, %rax",
        "    syscall",
        "    pop %rbx",
        "    cmp %r14, %rbx",
        "    jnz ywb_fail",
        "    cmp $-1, %r15",
        "    jz ywb_ok",
        "    mov 32(%rbp), %rax",
        "    add $8, %rax",
        "    mov %rax, %rsi",
        "    mov $-100, %rdi",
        "    mov %r15, %rdx",
        "    mov $268, %rax",
        "    syscall",
        "    cmp $0, %rax",
        "    jl ywb_fail",
        "ywb_ok:",
        "    mov $1, %rax",
        "    jmp ywb_done",
        "ywb_fail:",
        "    xor %eax, %eax",
        "ywb_done:",
        "    pop %r15",
        "    pop %r14",
        "    pop %r13",
        "    pop %r12",
        "    pop %rbx",
        "    pop %rbp",
        "    ret",
    ], "\n") + "\n"
};

def arch_consts() -> str {
    join([
        "ystr_nl: .ascii \"\\n\"",
        "ystr_true: .ascii \"true\"",
        "ystr_false: .ascii \"false\"",
        "ystr_true_h:",
        ".quad 4",
        ".string \"true\"",
        "ystr_false_h:",
        ".quad 5",
        ".string \"false\"",
        "ystr_minus_h:",
        ".quad 1",
        ".string \"-\"",
        "ystr_dot_h:",
        ".quad 1",
        ".string \".\"",
        "ystr_bigflt_h:",
        ".quad 23",
        ".string \"<float magnitude >2^63>\"",
        "ystr_divzero: .ascii \"runtime error: division by zero\\n\"",
        "ystr_divzero_end:",
        "ystr_oob: .ascii \"runtime error: index out of bounds\\n\"",
        "ystr_oob_end:",
        "ystr_dot: .ascii \"runtime error: record has no field '\"",
        "ystr_dot_end:",
        "ystr_dot2: .ascii \"'\\n\"",
        "ystr_dot2_end:",
        "ystr_oom: .ascii \"runtime error: out of memory\\n\"",
        "ystr_oom_end:",
        "ystr_opt: .ascii \"runtime error: unwrap of none\\n\"",
        "ystr_opt_end:",
    ], "\n") + "\n"
};

export { arch_id, arch_word, arch_sysno, arch_fn_label, arch_loc_label, arch_str_label, arch_header, arch_rodata, arch_text, arch_prelude, arch_consts, arch_frame, arch_exit };
