print(substr("hello world", 0, 5));
print(substr("hello", 2, 10));
print(substr("hello", 9, 3));
print(trim("  abc  "));
print(trim("   "));
print(ord("A"));
print(ord(""));
print(chr(66));
print(tonum("123"));
print(tonum("-45"));
print(tonum("12x"));
print(tostring(456));
print(tostring(-7));
print(tostring(true));
print(tostring("hi"));
print(index_of("hello", "ll"));
print(index_of("hello", "zz"));
print(last_index_of("aaa", "a"));
print(join(["a", "b", "c"], ","));
print(join([], ","));
let parts = split("a,b,c", ",");
print(len(parts));
print(parts[1]);
print("x" + tostring(1 + 2));
puts("nonl");
puts("X\n");
exit(0);
